### ISSUE TITLE
Create a Score-Board

### ISSUE THREAD

**Issue by dimitri-edel** [music-non-stop/music_non_stop#108]
**Acceptance criteria**
- [x] The score board reflects the top ten results
- [x] The results contain name of the player, score and time

**Tasks**
- [x] Define a function for adding results to the score-board
- [x] Define a function for loading results for the score-board
- [x] Render the results inside score-board.html
- [x] Define the JavaScript code in scoreboard.js
- [x] Dynamically add a link to the game in the navigation bar
