### ISSUE TITLE
Create Game Logic Class

### ISSUE THREAD

**Issue by dimitri-edel** [music-non-stop/music_non_stop#59]
**Acceptance criteria**
- [ ] Class encapsulates game logic and is Independent from the presentation tier
- [ ] Class keeps track of the score
- [ ] Class keeps track of which card is picked by the player
- [ ] When a card is picked, it plays the respective audio file
- [ ] Class enables the presentation components to determine if the game is over

**Tasks**
- [ ] Create class named Game in a separate file game.js
- [ ] Constructor takes an array of game card objects, mp3-player and a callback function for handling game-over
- [ ] Method pickCard that takes the index of the picked card as a parameter and returns true if the picked card matches the previously picked card
- [ ] The class calls the callback function that was passed in the parameter-list when the game is over
