### ISSUE TITLE
Create Game Card Class

### ISSUE THREAD

**Issue by dimitri-edel** [music-non-stop/music_non_stop#60]
**Acceptance criteria**
- [x] The class encapsulates any properties associated with a card in the game UI
- [x] The class can be easily extended
- [x] The class can render itself as an HTML object

**Tasks**
- [x] Class name GameCard
- [x] Property: index to hold the position of the card in the array of cards
- [x] Property: track-Index to hold the index of the audio file, that is associated with the card, in the playlist
- [x] Property: name holds the name of the associated audio file
- [x] Property: background-color of the flipside of the card
- [x] Property: image holds the path to the image associated with the card
- [x] All the properties are initialized using the parameter list
