### ISSUE TITLE
Create MP3 Player Class

### ISSUE THREAD

**Issue by dimitri-edel** [music-non-stop/music_non_stop#61]
**Acceptance criteria**
- [x] The class provides an easy way to load and play mp3-files
- [x] The player accepts a list of audio file names and loads them into its own playlist

**Task**
- [x] Name Class MP3Player
- [x] Constructor takes an array of names of audio-files and a string with a relative path to the audio folder
- [x] Class implements all the methods of an audio-player such as : play, pause, stop, previous, next
