### ISSUE TITLE
Create Game Presentation Container

### ISSUE THREAD

**Issue by dimitri-edel** [music-non-stop/music_non_stop#63]
** Acceptance criteria **
- [x] User can play the game
- [x] The game can be restarted
- [x] A User gets a feedback when the game is over
- [x] The container can be embedded on any webpage
- [x] The cards can be styled in a designated CSS file
- [x] The number of card pairs can be easily changed

**Tasks**
- [x] Crate an HTML page 
- [x] Java-Script file named main.js 
- [x] Define functions that use Game class and GameCards 
- [x] Create a list of audio-files that will be associated with the cards
- [x] Define function that generates an array with GameCards 
- [x] Define function for shuffling the cards, so they don't always appear in the same order
- [x] Define function for restarting the game
- [x] Define function for game-over and pass it to the Game constructor as a callback
- [x] Define a constant for number of card pairs to be used in the game
- [x] Define function for embedding game-cards in the DOM
- [x] Define function for removing game-cards from the DOM
- [x] Define function that defines what happens when a card is picked
- [x] Provide a separate CSS file for styling the cards
